version: '3.8'

services:
  app:
    image: crm-message-client:latest
    container_name: crm-message-client
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # volumes:
    #   - ./public:/app/public
    #   - ./.env:/app/.env

